# This file contains Jekyll configuration options.
#
# For site variables, head over to /_data
#
# These groups have been arranged alphabetically by header;
# feel free to toss them in whatever order suits you.

# Dependencies
markdown:    redcarpet
highlighter: pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from
# the index work properly.
permalink:           pretty
relative_permalinks: true

# Rakefile settings
post:
  template:  templates/_post.txt
  extension: md
page:
  template:  templates/_page.txt
  extension: md
recipe:
  template:  templates/_recipe.txt
  extension: html
editor: vim

# Sass settings
sass:
  sass_dir: _sass
  style:    :compressed

# Setup
baseurl:  /frommyfrontporch
paginate: 5
exclude:  [templates]
